# Machine Learning Part

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Prepare Clean Data

In [50]:
almond = pd.read_csv("Datasets/almond_clean.csv")

almond_onehot = almond.copy()

almond.head()

,length,width,thickness,area,perimeter,roundness,solidity,compactness,aspect_ratio,eccentricity,extent,convex_hull,type
0,321.807244,227.940628,127.759132,22619.0,643.813269,0.403849,0.973384,1.458265,1.923085,0.846328,0.681193,23237.5,MAMRA
1,321.807244,234.188126,128.199509,23038.0,680.984841,0.403849,0.957304,1.601844,1.923085,0.846328,0.656353,24065.5,MAMRA
2,321.807244,229.418610,125.796547,22386.5,646.943212,0.403849,0.967270,1.487772,1.923085,0.846328,0.683620,23144.0,MAMRA
3,321.807244,232.763153,125.918808,22578.5,661.227483,0.403849,0.965512,1.540979,1.923085,0.846328,0.685360,23385.0,MAMRA
4,321.807244,230.150742,107.253448,19068.0,624.842706,0.403849,0.951450,1.629395,1.923085,0.846328,0.714800,20041.0,MAMRA

## Encoding
Side note: Since we are dealing with almond classification, we don't need to onehot_encode the 'type' column. We don't need encoding at all.

In [51]:
#Use One-Hot Encoding to convert categorical variables into numerical format
almond_onehot = pd.get_dummies(almond_onehot, columns=['type'], drop_first=False)

In [52]:
almond_onehot

,length,width,thickness,area,perimeter,roundness,solidity,compactness,aspect_ratio,eccentricity,extent,convex_hull,type_MAMRA,type_REGULAR,type_SANORA
0,321.807244,227.940628,127.759132,22619.0,643.813269,0.403849,0.973384,1.458265,1.923085,0.846328,0.681193,23237.5,True,False,False
1,321.807244,234.188126,128.199509,23038.0,680.984841,0.403849,0.957304,1.601844,1.923085,0.846328,0.656353,24065.5,True,False,False
2,321.807244,229.418610,125.796547,22386.5,646.943212,0.403849,0.967270,1.487772,1.923085,0.846328,0.683620,23144.0,True,False,False
3,321.807244,232.763153,125.918808,22578.5,661.227483,0.403849,0.965512,1.540979,1.923085,0.846328,0.685360,23385.0,True,False,False
4,321.807244,230.150742,107.253448,19068.0,624.842706,0.403849,0.951450,1.629395,1.923085,0.846328,0.714800,20041.0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2798,283.245347,192.709366,122.356506,18471.5,653.345233,0.500045,0.931000,1.838965,1.634305,0.789078,0.725739,19840.5,False,False,True
2799,283.245347,186.254745,118.708961,17213.5,581.688379,0.500045,0.952706,1.564234,1.634305,0.789078,0.714016,18068.0,False,False,True
2800,283.245347,186.196182,119.147224,17510.5,608.315795,0.500045,0.948821,1.681705,1.634305,0.789078,0.718999,18455.0,False,False,True
2801,283.245347,188.660828,120.634438,17941.0,630.759446,0.500045,0.944810,1.764701,1.634305,0.789078,0.738191,18989.0,False,False,True
2802,269.356903,176.023636,115.371740,36683.5,887.310743,0.643761,0.947380,1.707933,1.530231,0.756930,0.722429,38721.0,False,False,True

## Scaling

### Using Standard Scaling for logistic regression

In [53]:
almond_standard_scaled = almond.copy()

#Standardize the numerical features
scaler = StandardScaler()
numerical_features = ['length', 'width', 'thickness', 'area', 'perimeter', 'aspect_ratio', 'convex_hull']
almond_standard_scaled[numerical_features] = scaler.fit_transform(almond_standard_scaled[numerical_features])

In [54]:
almond_standard_scaled

,length,width,thickness,area,perimeter,roundness,solidity,compactness,aspect_ratio,eccentricity,extent,convex_hull,type
0,0.586902,2.296827,1.166217,-0.282445,-0.433887,0.403849,0.973384,1.458265,1.109581,0.846328,0.681193,-0.313226,MAMRA
1,0.586902,2.548901,1.194369,-0.252039,-0.272686,0.403849,0.957304,1.601844,1.109581,0.846328,0.656353,-0.255059,MAMRA
2,0.586902,2.356461,1.040754,-0.299317,-0.420314,0.403849,0.967270,1.487772,1.109581,0.846328,0.683620,-0.319795,MAMRA
3,0.586902,2.491406,1.048569,-0.285384,-0.358367,0.403849,0.965512,1.540979,1.109581,0.846328,0.685360,-0.302865,MAMRA
4,0.586902,2.386001,-0.144665,-0.540135,-0.516157,0.403849,0.951450,1.629395,1.109581,0.846328,0.714800,-0.537782,MAMRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2798,-0.130134,0.875315,0.820840,-0.583422,-0.392550,0.500045,0.931000,1.838965,-0.704147,0.789078,0.725739,-0.551867,SANORA
2799,-0.130134,0.614884,0.587660,-0.674713,-0.703303,0.500045,0.952706,1.564234,-0.704147,0.789078,0.714016,-0.676386,SANORA
2800,-0.130134,0.612521,0.615677,-0.653160,-0.587829,0.500045,0.948821,1.681705,-0.704147,0.789078,0.718999,-0.649199,SANORA
2801,-0.130134,0.711964,0.710752,-0.621920,-0.490498,0.500045,0.944810,1.764701,-0.704147,0.789078,0.738191,-0.611685,SANORA
2802,-0.388382,0.202079,0.374319,0.738194,0.622084,0.643761,0.947380,1.707933,-1.357794,0.756930,0.722429,0.774495,SANORA

# Machine Learn Using Logistic Regression

## Predicting Almond Type

In [55]:
# Copy again
learning_data = almond_standard_scaled.copy()

In [58]:
# X = learning features
X = learning_data[['length', 'width', 'thickness', 'area', 'perimeter', 'roundness', 'solidity', 'compactness', 'aspect_ratio', 'eccentricity', 'extent', 'convex_hull']]

# y = target variable
y = learning_data[['type']]

print("Learning Features:")
print(X)
print("Target Variable:")
print(y)

Learning Features:
        length     width  thickness      area  perimeter  roundness  solidity  \
0     0.586902  2.296827   1.166217 -0.282445  -0.433887   0.403849  0.973384
1     0.586902  2.548901   1.194369 -0.252039  -0.272686   0.403849  0.957304
2     0.586902  2.356461   1.040754 -0.299317  -0.420314   0.403849  0.967270
3     0.586902  2.491406   1.048569 -0.285384  -0.358367   0.403849  0.965512
4     0.586902  2.386001  -0.144665 -0.540135  -0.516157   0.403849  0.951450
...        ...       ...        ...       ...        ...        ...       ...
2798 -0.130134  0.875315   0.820840 -0.583422  -0.392550   0.500045  0.931000
2799 -0.130134  0.614884   0.587660 -0.674713  -0.703303   0.500045  0.952706
2800 -0.130134  0.612521   0.615677 -0.653160  -0.587829   0.500045  0.948821
2801 -0.130134  0.711964   0.710752 -0.621920  -0.490498   0.500045  0.944810
2802 -0.388382  0.202079   0.374319  0.738194   0.622084   0.643761  0.947380

      compactness  aspect_ratio  eccentricity    extent  convex_hull
0        1.458265      1.109581      0.846328  0.681193    -0.313226
1        1.601844      1.109581      0.846328  0.656353    -0.255059
2        1.487772      1.109581      0.846328  0.683620    -0.319795
3        1.540979      1.109581      0.846328  0.685360    -0.302865
4        1.629395      1.109581      0.846328  0.714800    -0.537782
...           ...           ...           ...       ...          ...
2798     1.838965     -0.704147      0.789078  0.725739    -0.551867
2799     1.564234     -0.704147      0.789078  0.714016    -0.676386
2800     1.681705     -0.704147      0.789078  0.718999    -0.649199
2801     1.764701     -0.704147      0.789078  0.738191    -0.611685
2802     1.707933     -1.357794      0.756930  0.722429     0.774495

[2803 rows x 12 columns]
Target Variable:
        type
0      MAMRA
1      MAMRA
2      MAMRA
3      MAMRA
4      MAMRA
...      ...
2798  SANORA
2799  SANORA
2800  SANORA
2801  SANORA
2802  SANORA

[2803 rows x 1 columns]

## Train Test Splitting

In [ ]:
#Split le datos
#80% goes to training, 20% goes to testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape[0])
print("Testing set size:", X_test.shape[0])

Training set size: 2242
Testing set size: 561